Repository Nick-Sakach/HomePage, pull requests merged in 2019-05, with the labels that each got.

#4 First release! :-)
  README.md
  index.html
Labels: master

#10 Add base.css styling link
  index.html
Labels: enhancement

#15 Add primary content
  index.html
Labels: enhancement

#16 Add secondary content
  index.html
Labels: enhancement

#17 Feature/body
  index.html
Labels: enhancement

#18 Release all changes
  index.html
Labels: enhancement, master
